### ISSUE TITLE
[Teaser] The image authored is not rendered in the page

### ISSUE THREAD

**Issue by khn2475** [adobe/aem-react-core-wcm-components#18]
I configured an image in the teaser core component but the image is not being rendered in the webpage. The teaser core component model is not returning the imagePath value and hence the teaser typescript code is failing the render the image.
![Screenshot (140)](https://user-images.githubusercontent.com/73276680/96845885-d35d5780-146e-11eb-887d-f2dcc610c7b1.png)
![Screenshot (136)](https://user-images.githubusercontent.com/73276680/96845909-da846580-146e-11eb-8488-9eb5fff373ff.png)

**Comment by pfauchere** [comment]
This seems to be an issue with the Sling Model of the Teaser Core Component. Please open an issue in [0]

[0] https://github.com/adobe/aem-core-wcm-components

**Comment by niekraaijmakers** [comment]
Seems the imagePath should be exported in the sling model . For some reason it's not exported in the project here. Perhaps something is wrong in the project here.
